controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller/
        namespace: App\Shared\Infrastructure\Controller
    type: attribute

api_v1:
    resource: ../src/Notification/Infrastructure/Controller/v1
    type: attribute
    prefix: /api/v1
    name_prefix: api_v1_

webhooks:
    resource:
        path: ../src/Notification/Infrastructure/Webhook/Telegram
        namespace: App\Notification\Infrastructure\Webhook\Telegram
    type: attribute

kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.redocly:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.redocly }

app.stoplight:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.stoplight }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
