controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller/
        namespace: App\Shared\Infrastructure\Controller
    type: attribute


api_v1_subscription:
    resource: ../src/Notification/Infrastructure/Controller/v1/
    type: attribute
    prefix: /api/v1
    name_prefix: api_v1_

kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: attribute
