framework:
    messenger:
        failure_transport: failed
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
            event.bus:
            message.bus:
                default_middleware: allow_no_handlers

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'  # Основной транспорт
                retry_strategy:
                    max_retries: 3
                    delay: 1000    # Задержка между ретраями
                    multiplier: 2  # Увеличиваем задержку на 2 раза
                    max_delay: 30000  # Максимальная задержка между ретраями
            failed: '%env(MESSENGER_TRANSPORT_DEFAULT_DSN)%'
            external_messages:
                dsn: '%env(EXTERNAL_MESSAGE_TRANSPORT_DSN)%'
                serializer: 'messenger.transport.symfony_serializer'
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 30000
                options:
                    exchange:
                        name: '%env(EXTERNAL_MESSAGE_EXCHANGE)%'
                        type: 'direct'
                    queues:
                        phone_numbers:
                            binding_keys: [ 'phone' ]  # Будет получать только сообщения с routing_key = 'phone'
                            arguments:
                                'x-message-ttl': 600000  # 10 минут
                    auto_setup: true
        routing:
            # Route your messages to the transports
            'App\Notification\Domain\Message\ChannelVerificationCodeGetMessage': async  # Назначаем маршрут для наших сообщений
            'App\Notification\Domain\Message\ChannelVerificationFailedMessage': async
            'App\Notification\Domain\Message\ExternalMessage': external_messages


# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
