monolog:
    channels: [ 'notifier' ]
    handlers:
        file_log:
            action_level: warning
            type: rotating_file
            channels: [ "!event", "!security", "!doctrine", "!deprecation", "!request" ]
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            max_files: 10
            handler: error
        error:
            type: fingers_crossed
            # 500 errors are logged at the critical level
            action_level: error
            # to also log 400 level errors (but not 404's):
            # action_level: error
            excluded_http_codes: [ 401, 403, 404 ]
            channels: [ "!event", "!security", "!doctrine", "!deprecation", "!request", "!console", "!app" ]
            handler: deduplicated
        deduplicated:
            type: deduplication
            # the time in seconds during which duplicate entries are discarded (default: 60)
            time: 10
            handler: telegram
        telegram: # Важна только эта часть
            type: service
            id: telegram_handler
            channels: [ 'partner' ]
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: [ "!event", "!doctrine", "!console" ]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
